<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Decomp</RootNamespace>
    <AssemblyName>decomp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ICSharpCode.Decompiler">
      <HintPath>/Users/swear/.local/tools/ilspy/ILSpy.app/Contents/MacOS/ICSharpCode.Decompiler.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
