<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>dumpil</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>/Users/swear/.local/tools/ilspy/ILSpy.app/Contents/MacOS/Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
